env:
  node: true
  commonjs: true
  es2021: true
  mocha: true
extends:
  - eslint:recommended
  - plugin:mocha/recommended
parserOptions:
  ecmaVersion: latest
plugins:
  - mocha
rules:
  "no-unused-vars": ["error", { argsIgnorePattern: "^(next)$" }]
overrides:
  - files: "calc.test.js"
    env:
      mocha: true